#!/bin/sh

DIR=/dev/dsp1/

GLOBS=FILTER_COMMON
SITES=FILTER_SITES


cCrR() {
cat - <<EOF
        <pageFormat>
                <noCols>$1</noCols>
                <colItems>$2</colItems>
        </pageFormat> 
EOF
}

C1R10=/dev/shm/c1R10
C6R7=/dev/shm/c6R7

[ -e $C1R10 ] || cCrR 1 19 > $C1R10
[ -e $C6R7 ]  || cCrR 6 7 > $C6R7

dump_k() {
	(cd /dev/dsp1; 
	for file in $(find . -type f -print -maxdepth 1); do
		[ "$file" != "./.create" ] && echo $file $(cat $file)
	done
	)
}

dump_r() { (
	cd /dev/dsp1; 
	for file in [1-6]/*; do
		echo $file $(cat $file)
	done
	echo ..
	echo ..
) }

ADDED_WEB=0

add_web() {
if [ -e /var/www/d-tacq/acq_main_page.html ]; then
	grep -q $DEV /var/www/d-tacq/acq_main_page.html
	if [ $? -ne 0 ]; then
		sed -ie '/TABAPPEND/ {
a       <li><a title="'$GLOBS'" href="acq_info_page.html">'$GLOBS'</a></li>
a       <li><a title="'$SITES'" href="acq_info_page.html">'$SITES'</a></li>
}' /var/www/d-tacq/acq_main_page.html
	fi
	ADDED_WEB=1
fi
}

monitor() {
	while [ 1 ]
	do
		[ $ADDED_WEB -eq 0 ] && add_web				
		dump_k | fs2xml --kvp -o /dev/shm/$GLOBS.xml -s $C1R10
		dump_r | fs2xml --kvp -o /dev/shm/$SITES.xml -s $C6R7
		sleep 1		
	done
}

if [ "$(basename $0)" = "monitor_dsp1" ]; then
	if [ -d $DIR ]; then
		monitor
	else
		echo ERROR: monitor dir not found: $DIR
	fi
fi



