#!/bin/sh
# Reset and Enable the DSP module
cd /dev/dsp1
echo reset_then_enable_dsp before $(cat CTRL)
echo >CTRL.MOD_EN    1
echo >CTRL.DSP_RESET 1
echo >CTRL.EN 1
echo >CTRL.AUTO_RESET 1
echo >CTRL.DSP_RESET 0
echo reset_then_enable_dsp after $(cat CTRL)

